### ISSUE TITLE
missing resistor on parts list

### ISSUE THREAD

**Issue by gktval** [bvavra/MIDI_Accordion#14]
Just found the missing 2.2k ohm resistor to the bluetooth module. It's in the schematics, just not the parts list.

**Comment by bvavra** [comment]
Thanks for catching this!  I updated the parts list on both the [README](https://github.com/bvavra/MIDI_Accordion/blob/master/README.md) and the [Overview page](http://bvavra.github.io/MIDI_Accordion/overview/) accordingly.
