### ISSUE TITLE
Asking permission to use the code

### ISSUE THREAD

**Issue by M1nCh3** [bvavra/MIDI_Accordion#3]
Hi, my name is Wira, there is two thing i would say.
1. you realy done your  homework and you do awesome..salute!
2. just wondering if i just wanna use the code just to add more button on arduino mega without any air presure, so bassicly i just wanna make midi controller with 120 button, 16 potensio fader and 4 rotary encoder, is that possible if i use the code for it? and

**Comment by bvavra** [comment]
Hello Wira,

Thank you!  If you want to build a MIDI controller that's not an accordion, I'm not sure that my code will be the best fit as it is currently written.  You may certainly use it as you like (as it's under the GNU general public license), but the code is designed to scan two matrices of opto-interruptors, and for your project it may be a lot simpler to use digital buttons instead.  There are existing libraries and ICs out there that make digital button scanning easy, such as the [SX1509](https://www.sparkfun.com/products/13601), which supports scanning up to an 8x8 button pad.  You can add up to 4 of of these to a single Arduino to support up to 256 buttons - see [this guide](https://learn.sparkfun.com/tutorials/sx1509-io-expander-breakout-hookup-guide#example-button-matrices) for details.

Regarding the faders and encoders - the Arduino Mega has 16 analog pins, which is just enough to support 16 potentiometer faders, and if you offload the button matrix to an IC like the SX1509 you should still have plenty of digital pins to support 4 rotary encoders.  If you need more pins, you can use a [multiplexer](https://learn.sparkfun.com/tutorials/multiplexer-breakout-hookup-guide) to add more digital or analog pins.
