### ISSUE TITLE
BMP 085

### ISSUE THREAD

**Issue by denia85** [bvavra/MIDI_Accordion#6]
Installed bmp180 furs do not stretch and the sound is how to fix it?

**Comment by bvavra** [comment]
I'm sorry, I don't understand.  Can you provide me with more details regarding what problem you're having?

**Comment by bvavra** [comment]
Any more information you can provide?  Have you looked at [my tutorial page](http://bvavra.github.io/MIDI_Accordion/volume/) for this?  If so, can you show me which part you're having trouble with?

**Comment by bvavra** [comment]
Since I haven't heard any followup I'm going to close this issue.
